dataset_path: '../../dataset'
all_classes:
  - 'three'
  - 'bird'
  - 'no'
  - 'house'
  - 'four'
  - 'stop'
  - 'off'
  - 'eight'
  - 'marvin'
  - 'yes'
  - 'bed'
  - 'tree'
  - 'down'
  - 'wow'
  - 'up'
  - 'on'
  - 'one'
  - 'sheila'
  - 'seven'
  - 'happy'
  - 'five'
  - 'two'
  - 'go'
  - 'six'
  - 'right'
  - 'nine'
  - 'zero'
  - 'left'
  - 'cat'
  - 'dog'